language: ruby
rvm:
  - 2.1.8
  - 2.2.5
  - 2.3.1
gemfile:
  - test_rails_4_app/gemfiles/rails_4.0.gemfile
  - test_rails_4_app/gemfiles/rails_4.1.gemfile
  - test_rails_4_app/gemfiles/rails_4.2.gemfile
env:
  global:
    TRAVIS: true
sudo: false
cache: bundler
CODECLIMATE_REPO_TOKEN: 11158e372b49d660cd14d15f351b0326e7bcdd29e7e31f271a2055530212f3e3
